sudo: required

services:
  - docker

before_install:
  - docker pull obolibrary/odkfull

before_script:
  - cd src/ontology
  
script:
  - make test

#after_success:
#  coveralls

# whitelist
branches:
  only:
    - master
    - test-travis
    - rotationterms
    
notifications:
  email:
    - pbuttigi@mpi-bremen.de
    - m.a.laporte@cgiar.org
    - c.aubert@cgiar.org
