sudo: required

services:
  - docker

before_install:
  - docker pull obolibrary/odkfull

before_script:
  - cd src/ontology
  
script:
  - sh run.sh make test

#after_success:
#  coveralls

# whitelist
branches:
  only:
    - master
    - test-travis
    - rotationterms
    
notifications:
  email:
    - krishna.udaiwal@gmail.com
