name: Term - add new 
description: New term suggestion for AgrO
title: "[NTR] "
labels: [term-add]
assignees: KrishnaTO
body:
  - type: input
    id: term
    attributes:
      label: Proposed term label
      description: Please enter the label as found in a published source
      placeholder: "liming process"
    validations:
      required: true

  - type: textarea
    id: Synonyms
    attributes:
      label: Synonyms
    validations:
      required: false

  - type: textarea
    id: Definition
    attributes:
      label: Definition
      description: please give PubMed ID, if applicable [PMID:#######]
    validations:
      required: true

  - type: input
    id: Parent
    attributes:
      label: Parent term
      description: Please list term(s) which this term should be under? (Hint- [OLS](https://www.ebi.ac.uk/ols/ontologies/AgrO) allows east searching)
    validations:
      required: true

  - type: textarea
    id: Children
    attributes:
      label: Children terms
      description: Should any existing terms that should be moved underneath this new proposed term?
    validations:
      required: false

  - type: input
    id: attribution
    attributes:
      label: Your nano-attribution (ORCID)
      description: If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
    validations:
      required: false
