name: Custom issue template
description: When the issue isn't defined by other templates. Please provide as many references to resources mentioned as timely available.
assignees: krishnaTO
body:
  - type: checkboxes
    id: feature
    attributes:
      label: feature
      description: "Please check if this issue involves the following:"
      options:
        - label: "Feature Request"
        - label: "Help/Question on AgrO"

  - type: markdown
    attributes:
      value: "Note: For bug reports, please switch to the Typos/Bugs/Errors issue template"

  - type: textarea
    id: desc
    attributes:
      label: Please describe the issue in as much detail as possible
    validations:
      required: true
