name: Quality Control
description: Quality Control issues, addressing automated reports (ie. ROBOT report) or workflows modifications/suggestions
labels: [QC]
assignees: KrishnaTO
# Template originally forked from [@mondo](https://github.com/monarch-initiative/mondo/tree/master/.github/ISSUE_TEMPLATE) 
