name: Term - relabel
description: Suggested revised label (IAO_0000115) for a AgrO term.
title: '[Label] '
labels: [term-annot]
assignees: krishnaTO
body:
  - type: input
    id: term
    attributes:
      label: AgrO term
      description: ID and Label
      placeholder: "[liming process](http://purl.obolibrary.org/obo/AGRO_00000112)"
    validations:
      required: true

  - type: input
    id: label
    attributes:
      label: Suggested new label
    validations:
      required: true

  - type: textarea
    id: Additional
    attributes:
      label: Additional information
      description: Any additional information (like supporting evidence, PubMed ID, etc.)
    validations:
      required: false

  - type: input
    id: attribution
    attributes:
      label: Your nano-attribution (ORCID)
      description: If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
    validations:
      required: false

