name: Revise subclass relationship
description: Revise the subclass structure for AgrO terms; relating to `Equivalent To` or `SubClass Of` axioms for a term
title: "[Axiom] "
labels: [term-logic]
assignees: krishnaTO
body:
  - type: input
    id: term
    attributes:
      label: AgrO term
      description: ID and Label
      placeholder: "[liming process](http://purl.obolibrary.org/obo/AGRO_00000112)"
    validations:
      required: true

  - type: input
    id: revision
    attributes:
      label: Suggested revision
    validations:
      required: false

  - type: textarea
    id: reason
    attributes:
      label: Suggestion reasons
    validations:
      required: false

  - type: input
    id: attribution
    attributes:
      label: Your nano-attribution (ORCID)
      description: If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
    validations:
      required: false
