name: Term - definition revision
description: Change the textual definition of an AgrO term
title: "[Def] "
labels: [term-annot]
assignees: celineaubert
body:
  - type: input
    id: term
    attributes:
      label: AgrO term
      description: ID and Label
      placeholder: "[liming process](http://purl.obolibrary.org/obo/AGRO_00000112)"
    validations:
      required: true

  - type: textarea
    id: definition
    attributes:
      label: Suggested revision of textual definition
      description: Please include a source, like a website (or permalink)
    validations:
      required: false

  - type: input
    id: attribution
    attributes:
      label: Your nano-attribution (ORCID)
      description: If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
    validations:
      required: false
