name: Description Logics (DL) revision of term
description: Improve the OWL-DL statement (EquivalentTo, SubClassOf, etc) of a AgrO term
labels: [term-logic]
assignees: celineaubert
body:
  - type: input
    id: term
    attributes:
      label: AgrO term
      description: ID and Label
      placeholder: "[liming process](http://purl.obolibrary.org/obo/AGRO_00000112)"
    validations:
      required: true

  - type: textarea
    id: definition
    attributes:
      label: Suggested revision of logical definition
    validations:
      required: false

  - type: input
    id: attribution
    attributes:
      label: Your nano-attribution (ORCID)
      description: If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
    validations:
      required: false



