name: Term - fix/add xref (source link, ex. for definitions)
description: Report issue about incorrect xref source on term.
title: '[xRef] '
labels: [term-annot]
assignees: KrishnaTO
body:
  - type: input
    id: term
    attributes:
      label: AgrO term
      description: ID and Label
      placeholder: "[liming process](http://purl.obolibrary.org/obo/AGRO_00000112)"
    validations:
      required: true

  - type: textarea
    id: Xref
    attributes:
      label: Xref that should be fixed
      description: ID and label
    validations:
      required: false

  - type: textarea
    id: Comments
    attributes:
      label: Comments
    validations:
      required: false

  - type: input
    id: attribution
    attributes:
      label: Your nano-attribution (ORCID)
      description: If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
    validations:
      required: false

