name: Term - merge
description: Merge with another AgrO term and obsolete/deprecate an existing AgrO term
title: "[Merge] "
labels: [term-mod]
assignees: KrishnaTO
body:
  - type: input
    id: term
    attributes:
      label: AgrO term
      description: ID and Label
      placeholder: "[liming process](http://purl.obolibrary.org/obo/AGRO_00000112)"
    validations:
      required: true

  - type: textarea
    id: Reason
    attributes:
      label: Reason for deprecation
    validations:
      required: true

  - type: textarea
    id: merge
    attributes:
      label: Term to be merged with
    validations:
      required: true

  - type: input
    id: attribution
    attributes:
      label: Your nano-attribution (ORCID)
      description: If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
    validations:
      required: false


