name: Typos/Bugs/Errors
description: Report all kinds of typos or bugs in AgrO
labels: [bug]
assignees: KrishnaTO
# Template originally forked from [@mondo](https://github.com/monarch-initiative/mondo/tree/master/.github/ISSUE_TEMPLATE)
body:
  - type: input
    id: term
    attributes:
      label: AgrO term
      description: ID and Label
      placeholder: "[liming process](http://purl.obolibrary.org/obo/AGRO_00000112)"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug/Typo/Error description
    validations:
      required: false

  - type: input
    id: attribution
    attributes:
      label: Your nano-attribution (ORCID)
      description: If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
    validations:
      required: false
